[package]
name = "governance"
version = "0.5.0"
authors = ["Muta Dev <muta@nervos.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
muta = { git = "https://github.com/zeroqn/muta", branch = "fix-network-unidentified-session"}
protocol = { git = "https://github.com/zeroqn/muta", branch = "fix-network-unidentified-session", package = "muta-protocol" }
binding-macro = { git = "https://github.com/zeroqn/muta", branch = "fix-network-unidentified-session" }

asset = { path = "../asset" }
metadata = { path = "../metadata" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rlp = "0.4"
bytes = "0.5"
derive_more = "0.99"
byteorder = "1.3"
muta-codec-derive = "0.2"

[dev-dependencies]
cita_trie = "2.0"
async-trait = "0.1"
hex = "0.4"
toml = "0.5"
lazy_static = "1.4"
framework = { git = "https://github.com/zeroqn/muta", branch = "fix-network-unidentified-session"}
metadata = { path = "../metadata" }

